name: Test API and Publish Results

on:
  push:
    branches:
      - bbcworld  # Change this to your default branch if necessary
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name:  Working directory and contents report
        run: |
          pwd
          ls -1
          
      - name: Python pip package check
        run: |
          pip list

      - name: Run API test
        run: python test_api.py
        
      - name: Git diff for changes resulting from Action run
        run: git diff

      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add latest_response.txt
          git add results.txt
          git commit -m "Update API test results" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
